// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: url_shortener.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GrpcHandler_GetUrl_FullMethodName     = "/url_shortener.GrpcHandler/GetUrl"
	GrpcHandler_ShortenUrl_FullMethodName = "/url_shortener.GrpcHandler/ShortenUrl"
)

// GrpcHandlerClient is the client API for GrpcHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcHandlerClient interface {
	GetUrl(ctx context.Context, in *GetUrlRequest, opts ...grpc.CallOption) (*GetUrlResponse, error)
	ShortenUrl(ctx context.Context, in *ShortenUrlRequest, opts ...grpc.CallOption) (*ShortenUrlResponse, error)
}

type grpcHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcHandlerClient(cc grpc.ClientConnInterface) GrpcHandlerClient {
	return &grpcHandlerClient{cc}
}

func (c *grpcHandlerClient) GetUrl(ctx context.Context, in *GetUrlRequest, opts ...grpc.CallOption) (*GetUrlResponse, error) {
	out := new(GetUrlResponse)
	err := c.cc.Invoke(ctx, GrpcHandler_GetUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcHandlerClient) ShortenUrl(ctx context.Context, in *ShortenUrlRequest, opts ...grpc.CallOption) (*ShortenUrlResponse, error) {
	out := new(ShortenUrlResponse)
	err := c.cc.Invoke(ctx, GrpcHandler_ShortenUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcHandlerServer is the server API for GrpcHandler service.
// All implementations must embed UnimplementedGrpcHandlerServer
// for forward compatibility
type GrpcHandlerServer interface {
	GetUrl(context.Context, *GetUrlRequest) (*GetUrlResponse, error)
	ShortenUrl(context.Context, *ShortenUrlRequest) (*ShortenUrlResponse, error)
	mustEmbedUnimplementedGrpcHandlerServer()
}

// UnimplementedGrpcHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcHandlerServer struct {
}

func (UnimplementedGrpcHandlerServer) GetUrl(context.Context, *GetUrlRequest) (*GetUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedGrpcHandlerServer) ShortenUrl(context.Context, *ShortenUrlRequest) (*ShortenUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortenUrl not implemented")
}
func (UnimplementedGrpcHandlerServer) mustEmbedUnimplementedGrpcHandlerServer() {}

// UnsafeGrpcHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcHandlerServer will
// result in compilation errors.
type UnsafeGrpcHandlerServer interface {
	mustEmbedUnimplementedGrpcHandlerServer()
}

func RegisterGrpcHandlerServer(s grpc.ServiceRegistrar, srv GrpcHandlerServer) {
	s.RegisterService(&GrpcHandler_ServiceDesc, srv)
}

func _GrpcHandler_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHandlerServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHandler_GetUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHandlerServer).GetUrl(ctx, req.(*GetUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcHandler_ShortenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHandlerServer).ShortenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHandler_ShortenUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHandlerServer).ShortenUrl(ctx, req.(*ShortenUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcHandler_ServiceDesc is the grpc.ServiceDesc for GrpcHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "url_shortener.GrpcHandler",
	HandlerType: (*GrpcHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUrl",
			Handler:    _GrpcHandler_GetUrl_Handler,
		},
		{
			MethodName: "ShortenUrl",
			Handler:    _GrpcHandler_ShortenUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url_shortener.proto",
}
